# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://redfrogotr.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 10
summaryLength = 0

googlefonts = ["IBM Plex Sans", "Fira Mono"]
fontbody = 'IBM Plex Sans'
fontcode = 'Fira Mono'

[outputs]
  home = ["HTML", "RSS", "JSON"]
