baseURL = "https://github.com/jpanther/congo/v2"
disqusShortname = ""
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
paginate = 5
rssLimit = 10
# theme = "congo"
# theme = "smol"
# theme = "poison"
title = "Redfrogotr's Blog"

[author]
name = "Sean Sun"
email = "468027451@qq.com"

[taxonomies]
tags = "tags"
categories = "categories"
series = 'series'

# Parameters
[params]
subtitle = "The journey is the reward."
dateFmt = "2 January 2006"

# Header
[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 4

# Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/redfrogotr"
weight = 1

[[menu.footer]]
name = "X"
url = "https://x.com/SunLixin6"
weight = 2

[[menu.footer]]
name = "Mail"
url = "mailto:468027451@qq.com"
weight = 3
